micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${SERVERPORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DATASOURCE_URL:`jdbc:mysql://localhost:3306/km_grpc?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

itau:
  erp:
    url: http://localhost:9091/api/v1/clientes
